export const MATERIAL_LIBRARY_VERSION = "2026.03.09";

export const MATERIAL_LIBRARY = [
  {
    id: "cu_etp_c110",
    name: "Copper (ETP)",
    category: "Metals",
    grade: "C11000",
    description: "High-conductivity copper for windings and conductors.",
    source: "ASM Handbook + IEC reference values",
    constants: {
      resistivity_ohm_m: 1.724e-8,
      conductivity_s_m: 5.8e7,
      temp_coeff_resistance: 0.00393,
      thermal_conductivity_w_mk: 401,
      density_kg_m3: 8960,
      specific_heat_j_kgk: 385,
      youngs_modulus_gpa: 110,
      armature_resistance: 0.42,
      armature_inductance: 0.0026,
    },
  },
  {
    id: "al_6061_t6",
    name: "Aluminium 6061-T6",
    category: "Metals",
    grade: "6061-T6",
    description: "General structural aluminium alloy.",
    source: "ASM MatWeb typical values",
    constants: {
      resistivity_ohm_m: 3.99e-8,
      conductivity_s_m: 2.5e7,
      thermal_conductivity_w_mk: 167,
      density_kg_m3: 2700,
      specific_heat_j_kgk: 896,
      youngs_modulus_gpa: 68.9,
      poisson_ratio: 0.33,
    },
  },
  {
    id: "steel_aisi_1018",
    name: "Carbon Steel",
    category: "Metals",
    grade: "AISI 1018",
    description: "Common low-carbon steel for shafts and mechanical frames.",
    source: "ASM steels databook",
    constants: {
      resistivity_ohm_m: 1.59e-7,
      thermal_conductivity_w_mk: 51.9,
      density_kg_m3: 7870,
      specific_heat_j_kgk: 486,
      youngs_modulus_gpa: 205,
      poisson_ratio: 0.29,
      friction_coeff: 0.0009,
      inertia_j: 0.0025,
    },
  },
  {
    id: "electrical_steel_m19",
    name: "Electrical Steel",
    category: "Magnetic",
    grade: "M19",
    description: "Silicon steel for motor stator/rotor cores.",
    source: "Manufacturer datasheet averages",
    constants: {
      density_kg_m3: 7650,
      specific_heat_j_kgk: 460,
      thermal_conductivity_w_mk: 23,
      relative_permeability: 4000,
      saturation_flux_density_t: 1.95,
      core_loss_w_kg_50hz_1_5t: 2.2,
    },
  },
  {
    id: "ndfeb_n42",
    name: "NdFeB Magnet",
    category: "Magnetic",
    grade: "N42",
    description: "Permanent magnet material used in PM motors.",
    source: "Magnet manufacturer datasheet",
    constants: {
      density_kg_m3: 7500,
      remanence_t: 1.3,
      coercivity_ka_m: 955,
      relative_permeability: 1.05,
      back_emf_constant: 0.072,
      torque_constant: 0.072,
    },
  },
  {
    id: "ferrite_mnzn",
    name: "Ferrite (MnZn)",
    category: "Magnetic",
    grade: "Power Ferrite",
    description: "Magnetic ferrite for inductive high-frequency components.",
    source: "Power ferrite catalog typical values",
    constants: {
      density_kg_m3: 4800,
      relative_permeability: 2300,
      saturation_flux_density_t: 0.45,
      thermal_conductivity_w_mk: 5,
      specific_heat_j_kgk: 750,
    },
  },
  {
    id: "silicon_intrinsic",
    name: "Silicon",
    category: "Semiconductors",
    grade: "Intrinsic",
    description: "Base semiconductor material for electronics and MEMS.",
    source: "Semiconductor reference data",
    constants: {
      bandgap_ev: 1.12,
      thermal_conductivity_w_mk: 148,
      density_kg_m3: 2330,
      specific_heat_j_kgk: 700,
      dielectric_constant: 11.7,
    },
  },
  {
    id: "sic_4h",
    name: "Silicon Carbide",
    category: "Semiconductors",
    grade: "4H-SiC",
    description: "Wide-bandgap semiconductor for high-power drives.",
    source: "Device handbook references",
    constants: {
      bandgap_ev: 3.26,
      thermal_conductivity_w_mk: 370,
      density_kg_m3: 3210,
      dielectric_constant: 9.7,
    },
  },
  {
    id: "gan",
    name: "Gallium Nitride",
    category: "Semiconductors",
    grade: "GaN",
    description: "Wide-bandgap semiconductor for high-frequency switching.",
    source: "GaN materials database",
    constants: {
      bandgap_ev: 3.4,
      thermal_conductivity_w_mk: 130,
      density_kg_m3: 6150,
      dielectric_constant: 9.5,
    },
  },
  {
    id: "kapton_polyimide",
    name: "Kapton Polyimide",
    category: "Insulators",
    grade: "HN",
    description: "Insulation film for motor windings and flex circuits.",
    source: "DuPont datasheet typical",
    constants: {
      density_kg_m3: 1420,
      thermal_conductivity_w_mk: 0.12,
      specific_heat_j_kgk: 1090,
      dielectric_strength_kv_mm: 7.8,
      dielectric_constant: 3.4,
    },
  },
  {
    id: "epoxy_resin",
    name: "Epoxy Resin",
    category: "Insulators",
    grade: "Electrical Potting",
    description: "General electrical insulation and potting compound.",
    source: "Industrial datasheet range midpoints",
    constants: {
      density_kg_m3: 1200,
      thermal_conductivity_w_mk: 0.21,
      specific_heat_j_kgk: 1100,
      dielectric_constant: 3.7,
      dielectric_strength_kv_mm: 17,
    },
  },
  {
    id: "ptfe",
    name: "PTFE",
    category: "Insulators",
    grade: "Virgin PTFE",
    description: "Low-friction insulator polymer.",
    source: "Polymer engineering handbook",
    constants: {
      density_kg_m3: 2200,
      thermal_conductivity_w_mk: 0.25,
      specific_heat_j_kgk: 1000,
      dielectric_constant: 2.1,
      friction_coeff: 0.04,
    },
  },
  {
    id: "brass_c360",
    name: "Brass",
    category: "Metals",
    grade: "C36000",
    description: "Machinable copper-zinc alloy used in connectors and fixtures.",
    source: "ASM alloy tables",
    constants: {
      resistivity_ohm_m: 6.2e-8,
      thermal_conductivity_w_mk: 121,
      density_kg_m3: 8530,
      specific_heat_j_kgk: 380,
      youngs_modulus_gpa: 97,
    },
  },
  {
    id: "titanium_ti6al4v",
    name: "Titanium Alloy",
    category: "Metals",
    grade: "Ti-6Al-4V",
    description: "High-strength low-density alloy for high performance rotors/structures.",
    source: "Aerospace material handbook",
    constants: {
      resistivity_ohm_m: 1.78e-6,
      thermal_conductivity_w_mk: 6.7,
      density_kg_m3: 4430,
      specific_heat_j_kgk: 560,
      youngs_modulus_gpa: 114,
      poisson_ratio: 0.34,
    },
  },
  {
    id: "nickel_200",
    name: "Nickel",
    category: "Metals",
    grade: "Nickel 200",
    description: "High-temperature and corrosion-resistant conductive material.",
    source: "Nickel alloy datasheet",
    constants: {
      resistivity_ohm_m: 6.99e-8,
      thermal_conductivity_w_mk: 90.9,
      density_kg_m3: 8908,
      specific_heat_j_kgk: 440,
      youngs_modulus_gpa: 207,
    },
  },
  {
    id: "stainless_304",
    name: "Stainless Steel",
    category: "Metals",
    grade: "AISI 304",
    description: "Corrosion resistant steel for enclosures and shafts.",
    source: "Stainless handbook",
    constants: {
      resistivity_ohm_m: 7.2e-7,
      thermal_conductivity_w_mk: 16.2,
      density_kg_m3: 8000,
      specific_heat_j_kgk: 500,
      youngs_modulus_gpa: 193,
      poisson_ratio: 0.29,
    },
  },
  {
    id: "graphite",
    name: "Graphite",
    category: "Carbon",
    grade: "Electrographite",
    description: "Used in brushes and high-temp electrical interfaces.",
    source: "Carbon engineering datasheet",
    constants: {
      resistivity_ohm_m: 1.5e-5,
      thermal_conductivity_w_mk: 120,
      density_kg_m3: 1750,
      specific_heat_j_kgk: 710,
      friction_coeff: 0.15,
    },
  },
  {
    id: "carbon_fiber_epoxy",
    name: "Carbon Fiber Composite",
    category: "Composites",
    grade: "UD CFRP",
    description: "High stiffness composite for lightweight rotor and structural parts.",
    source: "Composite design handbook",
    constants: {
      density_kg_m3: 1600,
      youngs_modulus_gpa: 135,
      poisson_ratio: 0.28,
      thermal_conductivity_w_mk: 6,
      specific_heat_j_kgk: 900,
    },
  },
  {
    id: "mica",
    name: "Mica",
    category: "Insulators",
    grade: "Electrical Grade",
    description: "High dielectric strength mineral insulator for slot insulation.",
    source: "Electrical insulation data handbook",
    constants: {
      density_kg_m3: 2800,
      thermal_conductivity_w_mk: 0.5,
      specific_heat_j_kgk: 790,
      dielectric_constant: 6,
      dielectric_strength_kv_mm: 20,
    },
  },
  {
    id: "neoprene",
    name: "Neoprene",
    category: "Polymers",
    grade: "CR Rubber",
    description: "Seal and vibration damping elastomer.",
    source: "Polymer material handbook",
    constants: {
      density_kg_m3: 1230,
      thermal_conductivity_w_mk: 0.2,
      specific_heat_j_kgk: 1460,
      youngs_modulus_gpa: 0.01,
      friction_coeff: 0.6,
    },
  },
  {
    id: "magnesium_az31b",
    name: "Magnesium Alloy",
    category: "Metals",
    grade: "AZ31B",
    description: "Very lightweight structural alloy.",
    source: "Alloy property database",
    constants: {
      resistivity_ohm_m: 9.2e-8,
      thermal_conductivity_w_mk: 96,
      density_kg_m3: 1770,
      specific_heat_j_kgk: 1020,
      youngs_modulus_gpa: 45,
      poisson_ratio: 0.35,
    },
  },
  {
    id: "silver",
    name: "Silver",
    category: "Metals",
    grade: "High Purity",
    description: "Highest electrical conductivity reference conductor.",
    source: "Physical constants tables",
    constants: {
      resistivity_ohm_m: 1.59e-8,
      conductivity_s_m: 6.3e7,
      thermal_conductivity_w_mk: 429,
      density_kg_m3: 10490,
      specific_heat_j_kgk: 235,
      temp_coeff_resistance: 0.0038,
    },
  },
];
