/**
 * TemplateRegistry.js
 * Pre-built circuit templates with real node/edge data.
 * Each template can be loaded directly into the React Flow canvas.
 */

const TemplateRegistry = [
  {
    id: "temp-pressure-chain",
    name: "Temperature → Pressure Chain",
    desc: "Two temperature sensors feeding a single pressure sensor for a simple layered flow.",
    icon: "🧪",
    complexity: 1,
    nodes: [
      {
        id: "tpl-temp-1",
        type: "temperature_sensor",
        position: { x: 80, y: 120 },
        data: { label: "Temp Sensor A" },
      },
      {
        id: "tpl-temp-2",
        type: "temperature_sensor",
        position: { x: 80, y: 320 },
        data: { label: "Temp Sensor B" },
      },
      {
        id: "tpl-pressure-1",
        type: "pressure_sensor",
        position: { x: 320, y: 220 },
        data: { label: "Pressure Sensor" },
      },
    ],
    edges: [
      {
        id: "tpl-edge-1",
        source: "tpl-temp-1",
        sourceHandle: "measured_temp",
        target: "tpl-pressure-1",
        targetHandle: "flow_rate",
      },
      {
        id: "tpl-edge-2",
        source: "tpl-temp-2",
        sourceHandle: "measured_temp",
        target: "tpl-pressure-1",
        targetHandle: "valve_restriction",
      },
    ],
  },
  {
    id: "heat-control-loop",
    name: "Heat Control Loop",
    desc: "Temperature sensor output feeds a custom gain node before actuating pressure.",
    icon: "♻️",
    complexity: 2,
    nodes: [
      {
        id: "tpl-temp-3",
        type: "temperature_sensor",
        position: { x: 60, y: 180 },
        data: { label: "Measured Temp" },
      },
      {
        id: "tpl-custom-gain",
        type: "custom_formula",
        position: { x: 260, y: 160 },
        data: {
          label: "Gain Logic",
          customInputs: ["measured_temp"],
          customOutputs: ["control_signal"],
          customFormulas: {
            control_signal: "measured_temp * 1.2 + 0.5",
          },
        },
      },
      {
        id: "tpl-pressure-2",
        type: "pressure_sensor",
        position: { x: 480, y: 200 },
        data: { label: "Actuated Pressure" },
      },
    ],
    edges: [
      {
        id: "tpl-edge-3",
        source: "tpl-temp-3",
        sourceHandle: "measured_temp",
        target: "tpl-custom-gain",
        targetHandle: "measured_temp",
      },
      {
        id: "tpl-edge-4",
        source: "tpl-custom-gain",
        sourceHandle: "control_signal",
        target: "tpl-pressure-2",
        targetHandle: "flow_rate",
      },
    ],
  },
  {
    id: "parallel-temperature-array",
    name: "Parallel Temperature Array",
    desc: "Three sensors average their readings before driving a single pressure output.",
    icon: "🔀",
    complexity: 3,
    nodes: [
      {
        id: "tpl3-temp-1",
        type: "temperature_sensor",
        position: { x: 60, y: 80 },
        data: { label: "Temp Sensor A" },
      },
      {
        id: "tpl3-temp-2",
        type: "temperature_sensor",
        position: { x: 60, y: 220 },
        data: { label: "Temp Sensor B" },
      },
      {
        id: "tpl3-temp-3",
        type: "temperature_sensor",
        position: { x: 60, y: 360 },
        data: { label: "Temp Sensor C" },
      },
      {
        id: "tpl3-avg-math",
        type: "custom_formula",
        position: { x: 280, y: 220 },
        data: {
          label: "Avg + Bias",
          customInputs: ["measured_temp_A", "measured_temp_B", "measured_temp_C"],
          customOutputs: ["avg_temp"],
          customFormulas: {
            avg_temp: "(measured_temp_A + measured_temp_B + measured_temp_C) / 3 + 0.1",
          },
        },
      },
      {
        id: "tpl3-pressure-1",
        type: "pressure_sensor",
        position: { x: 520, y: 220 },
        data: { label: "Balanced Pressure" },
      },
    ],
    edges: [
      {
        id: "tpl3-edge-1",
        source: "tpl3-temp-1",
        sourceHandle: "measured_temp",
        target: "tpl3-avg-math",
        targetHandle: "measured_temp_A",
      },
      {
        id: "tpl3-edge-2",
        source: "tpl3-temp-2",
        sourceHandle: "measured_temp",
        target: "tpl3-avg-math",
        targetHandle: "measured_temp_B",
      },
      {
        id: "tpl3-edge-3",
        source: "tpl3-temp-3",
        sourceHandle: "measured_temp",
        target: "tpl3-avg-math",
        targetHandle: "measured_temp_C",
      },
      {
        id: "tpl3-edge-4",
        source: "tpl3-avg-math",
        sourceHandle: "avg_temp",
        target: "tpl3-pressure-1",
        targetHandle: "flow_rate",
      },
      {
        id: "tpl3-edge-5",
        source: "tpl3-avg-math",
        sourceHandle: "avg_temp",
        target: "tpl3-pressure-1",
        targetHandle: "valve_restriction",
      },
    ],
  },
  {
    id: "feedback-boost",
    name: "Feedback Boost Loop",
    desc: "Pressure is measured, fed through controllers, and re-actuated for stronger flow.",
    icon: "⚡",
    complexity: 4,
    nodes: [
      {
        id: "tpl4-temp",
        type: "temperature_sensor",
        position: { x: 40, y: 200 },
        data: { label: "Thermal Input" },
      },
      {
        id: "tpl4-pressure-raw",
        type: "pressure_sensor",
        position: { x: 260, y: 120 },
        data: { label: "Raw Pressure" },
      },
      {
        id: "tpl4-controller",
        type: "custom_formula",
        position: { x: 460, y: 120 },
        data: {
          label: "Controller",
          customInputs: ["measured_pressure", "measured_temp"],
          customOutputs: ["control_signal"],
          customFormulas: {
            control_signal: "measured_temp * 0.2 + measured_pressure * 0.15 + 1",
          },
        },
      },
      {
        id: "tpl4-adjuster",
        type: "custom_formula",
        position: { x: 660, y: 180 },
        data: {
          label: "Adjuster",
          customInputs: ["control_signal", "measured_pressure"],
          customOutputs: ["adjusted_flow"],
          customFormulas: {
            adjusted_flow: "control_signal * 1.1 - measured_pressure * 0.05",
          },
        },
      },
      {
        id: "tpl4-pressure-final",
        type: "pressure_sensor",
        position: { x: 880, y: 200 },
        data: { label: "Actuated Pressure" },
      },
    ],
    edges: [
      {
        id: "tpl4-edge-1",
        source: "tpl4-temp",
        sourceHandle: "measured_temp",
        target: "tpl4-pressure-raw",
        targetHandle: "flow_rate",
      },
      {
        id: "tpl4-edge-2",
        source: "tpl4-pressure-raw",
        sourceHandle: "measured_pressure",
        target: "tpl4-controller",
        targetHandle: "measured_pressure",
      },
      {
        id: "tpl4-edge-3",
        source: "tpl4-temp",
        sourceHandle: "measured_temp",
        target: "tpl4-controller",
        targetHandle: "measured_temp",
      },
      {
        id: "tpl4-edge-4",
        source: "tpl4-controller",
        sourceHandle: "control_signal",
        target: "tpl4-adjuster",
        targetHandle: "control_signal",
      },
      {
        id: "tpl4-edge-5",
        source: "tpl4-pressure-raw",
        sourceHandle: "measured_pressure",
        target: "tpl4-adjuster",
        targetHandle: "measured_pressure",
      },
      {
        id: "tpl4-edge-6",
        source: "tpl4-adjuster",
        sourceHandle: "adjusted_flow",
        target: "tpl4-pressure-final",
        targetHandle: "flow_rate",
      },
      {
        id: "tpl4-edge-7",
        source: "tpl4-adjuster",
        sourceHandle: "adjusted_flow",
        target: "tpl4-pressure-final",
        targetHandle: "valve_restriction",
      },
    ],
  },
  {
    id: "cascade-calibration",
    name: "Cascade Calibration",
    desc: "Dual sensors calibrate together, then a valve calibrator nudges final pressure.",
    icon: "🛠️",
    complexity: 5,
    nodes: [
      {
        id: "tpl5-temp-1",
        type: "temperature_sensor",
        position: { x: 40, y: 140 },
        data: { label: "Primary Temp" },
      },
      {
        id: "tpl5-temp-2",
        type: "temperature_sensor",
        position: { x: 40, y: 260 },
        data: { label: "Secondary Temp" },
      },
      {
        id: "tpl5-offset",
        type: "custom_formula",
        position: { x: 280, y: 200 },
        data: {
          label: "Calibrated Temp",
          customInputs: ["measured_temp_A", "measured_temp_B"],
          customOutputs: ["calibrated_temp"],
          customFormulas: {
            calibrated_temp: "(measured_temp_A * 0.6 + measured_temp_B * 0.4) + 0.2",
          },
        },
      },
      {
        id: "tpl5-pressure-1",
        type: "pressure_sensor",
        position: { x: 520, y: 120 },
        data: { label: "Primary Pressure" },
      },
      {
        id: "tpl5-calibrator",
        type: "custom_formula",
        position: { x: 520, y: 320 },
        data: {
          label: "Valve Calibrator",
          customInputs: ["calibrated_temp", "measured_pressure"],
          customOutputs: ["valve_restriction"],
          customFormulas: {
            valve_restriction: "Math.max(0, calibrated_temp - measured_pressure * 0.1)",
          },
        },
      },
      {
        id: "tpl5-pressure-2",
        type: "pressure_sensor",
        position: { x: 740, y: 240 },
        data: { label: "Calibrated Output" },
      },
    ],
    edges: [
      {
        id: "tpl5-edge-1",
        source: "tpl5-temp-1",
        sourceHandle: "measured_temp",
        target: "tpl5-offset",
        targetHandle: "measured_temp_A",
      },
      {
        id: "tpl5-edge-2",
        source: "tpl5-temp-2",
        sourceHandle: "measured_temp",
        target: "tpl5-offset",
        targetHandle: "measured_temp_B",
      },
      {
        id: "tpl5-edge-3",
        source: "tpl5-offset",
        sourceHandle: "calibrated_temp",
        target: "tpl5-pressure-1",
        targetHandle: "flow_rate",
      },
      {
        id: "tpl5-edge-4",
        source: "tpl5-pressure-1",
        sourceHandle: "measured_pressure",
        target: "tpl5-calibrator",
        targetHandle: "measured_pressure",
      },
      {
        id: "tpl5-edge-5",
        source: "tpl5-offset",
        sourceHandle: "calibrated_temp",
        target: "tpl5-calibrator",
        targetHandle: "calibrated_temp",
      },
      {
        id: "tpl5-edge-6",
        source: "tpl5-calibrator",
        sourceHandle: "valve_restriction",
        target: "tpl5-pressure-2",
        targetHandle: "valve_restriction",
      },
      {
        id: "tpl5-edge-7",
        source: "tpl5-offset",
        sourceHandle: "calibrated_temp",
        target: "tpl5-pressure-2",
        targetHandle: "flow_rate",
      },
    ],
  },
  {
    id: "split-flow-controller",
    name: "Split Flow Controller",
    desc: "One pressure measurement splits into two branches and loops back a safety signal.",
    icon: "🧭",
    complexity: 6,
    nodes: [
      {
        id: "tpl6-temp",
        type: "temperature_sensor",
        position: { x: 40, y: 200 },
        data: { label: "Main Thermal" },
      },
      {
        id: "tpl6-pressure-main",
        type: "pressure_sensor",
        position: { x: 260, y: 200 },
        data: { label: "Main Pressure" },
      },
      {
        id: "tpl6-splitter",
        type: "custom_formula",
        position: { x: 480, y: 200 },
        data: {
          label: "Split Logic",
          customInputs: ["measured_pressure"],
          customOutputs: ["branch_flow_a", "branch_flow_b"],
          customFormulas: {
            branch_flow_a: "measured_pressure * 0.6",
            branch_flow_b: "measured_pressure * 0.4",
          },
        },
      },
      {
        id: "tpl6-pressure-branch-a",
        type: "pressure_sensor",
        position: { x: 700, y: 80 },
        data: { label: "Branch A" },
      },
      {
        id: "tpl6-pressure-branch-b",
        type: "pressure_sensor",
        position: { x: 700, y: 320 },
        data: { label: "Branch B" },
      },
      {
        id: "tpl6-safety-check",
        type: "custom_formula",
        position: { x: 900, y: 200 },
        data: {
          label: "Safety Check",
          customInputs: ["measured_pressure_a", "measured_pressure_b"],
          customOutputs: ["control_signal"],
          customFormulas: {
            control_signal: "Math.min(measured_pressure_a, measured_pressure_b) * 0.1",
          },
        },
      },
    ],
    edges: [
      {
        id: "tpl6-edge-1",
        source: "tpl6-temp",
        sourceHandle: "measured_temp",
        target: "tpl6-pressure-main",
        targetHandle: "flow_rate",
      },
      {
        id: "tpl6-edge-2",
        source: "tpl6-pressure-main",
        sourceHandle: "measured_pressure",
        target: "tpl6-splitter",
        targetHandle: "measured_pressure",
      },
      {
        id: "tpl6-edge-3",
        source: "tpl6-splitter",
        sourceHandle: "branch_flow_a",
        target: "tpl6-pressure-branch-a",
        targetHandle: "flow_rate",
      },
      {
        id: "tpl6-edge-4",
        source: "tpl6-splitter",
        sourceHandle: "branch_flow_b",
        target: "tpl6-pressure-branch-b",
        targetHandle: "flow_rate",
      },
      {
        id: "tpl6-edge-5",
        source: "tpl6-pressure-branch-a",
        sourceHandle: "measured_pressure",
        target: "tpl6-safety-check",
        targetHandle: "measured_pressure_a",
      },
      {
        id: "tpl6-edge-6",
        source: "tpl6-pressure-branch-b",
        sourceHandle: "measured_pressure",
        target: "tpl6-safety-check",
        targetHandle: "measured_pressure_b",
      },
      {
        id: "tpl6-edge-7",
        source: "tpl6-safety-check",
        sourceHandle: "control_signal",
        target: "tpl6-pressure-main",
        targetHandle: "valve_restriction",
      },
    ],
  },
  {
    id: "dual-pressure-balancer",
    name: "Dual Pressure Balancer",
    desc: "Two pressure paths converge into a mixer that feeds a tertiary output.",
    icon: "🧮",
    complexity: 7,
    nodes: [
      {
        id: "tpl7-temp-1",
        type: "temperature_sensor",
        position: { x: 40, y: 160 },
        data: { label: "Temp Sensor Alpha" },
      },
      {
        id: "tpl7-temp-2",
        type: "temperature_sensor",
        position: { x: 40, y: 280 },
        data: { label: "Temp Sensor Beta" },
      },
      {
        id: "tpl7-pressure-1",
        type: "pressure_sensor",
        position: { x: 260, y: 160 },
        data: { label: "Pressure Channel 1" },
      },
      {
        id: "tpl7-pressure-2",
        type: "pressure_sensor",
        position: { x: 260, y: 280 },
        data: { label: "Pressure Channel 2" },
      },
      {
        id: "tpl7-balancer",
        type: "custom_formula",
        position: { x: 480, y: 220 },
        data: {
          label: "Balancer",
          customInputs: ["measured_pressure_1", "measured_pressure_2"],
          customOutputs: ["balanced_flow"],
          customFormulas: {
            balanced_flow: "(measured_pressure_1 + measured_pressure_2) / 2",
          },
        },
      },
      {
        id: "tpl7-mixer",
        type: "custom_formula",
        position: { x: 640, y: 200 },
        data: {
          label: "Flow Mixer",
          customInputs: ["balanced_flow"],
          customOutputs: ["mixed_flow"],
          customFormulas: {
            mixed_flow: "balanced_flow * 0.9",
          },
        },
      },
      {
        id: "tpl7-pressure-output",
        type: "pressure_sensor",
        position: { x: 820, y: 200 },
        data: { label: "Balanced Output" },
      },
    ],
    edges: [
      {
        id: "tpl7-edge-1",
        source: "tpl7-temp-1",
        sourceHandle: "measured_temp",
        target: "tpl7-pressure-1",
        targetHandle: "flow_rate",
      },
      {
        id: "tpl7-edge-2",
        source: "tpl7-temp-2",
        sourceHandle: "measured_temp",
        target: "tpl7-pressure-2",
        targetHandle: "flow_rate",
      },
      {
        id: "tpl7-edge-3",
        source: "tpl7-pressure-1",
        sourceHandle: "measured_pressure",
        target: "tpl7-balancer",
        targetHandle: "measured_pressure_1",
      },
      {
        id: "tpl7-edge-4",
        source: "tpl7-pressure-2",
        sourceHandle: "measured_pressure",
        target: "tpl7-balancer",
        targetHandle: "measured_pressure_2",
      },
      {
        id: "tpl7-edge-5",
        source: "tpl7-balancer",
        sourceHandle: "balanced_flow",
        target: "tpl7-mixer",
        targetHandle: "balanced_flow",
      },
      {
        id: "tpl7-edge-6",
        source: "tpl7-mixer",
        sourceHandle: "mixed_flow",
        target: "tpl7-pressure-output",
        targetHandle: "flow_rate",
      },
      {
        id: "tpl7-edge-7",
        source: "tpl7-mixer",
        sourceHandle: "mixed_flow",
        target: "tpl7-pressure-output",
        targetHandle: "valve_restriction",
      },
    ],
  },
  {
    id: "sensor-fusion-network",
    name: "Sensor Fusion Network",
    desc: "Three temperature sensors feed fusion and deviation math before the pressure output.",
    icon: "🧠",
    complexity: 8,
    nodes: [
      {
        id: "tpl8-temp-1",
        type: "temperature_sensor",
        position: { x: 40, y: 120 },
        data: { label: "Temp 1" },
      },
      {
        id: "tpl8-temp-2",
        type: "temperature_sensor",
        position: { x: 40, y: 240 },
        data: { label: "Temp 2" },
      },
      {
        id: "tpl8-temp-3",
        type: "temperature_sensor",
        position: { x: 40, y: 360 },
        data: { label: "Temp 3" },
      },
      {
        id: "tpl8-aggregator",
        type: "custom_formula",
        position: { x: 280, y: 200 },
        data: {
          label: "Fusion Sum",
          customInputs: ["t1", "t2", "t3"],
          customOutputs: ["sum_temp"],
          customFormulas: {
            sum_temp: "(t1 + t2 + t3) / 3",
          },
        },
      },
      {
        id: "tpl8-differencer",
        type: "custom_formula",
        position: { x: 520, y: 120 },
        data: {
          label: "Deviation",
          customInputs: ["sum_temp", "t1"],
          customOutputs: ["deviation"],
          customFormulas: {
            deviation: "Math.abs(sum_temp - t1)",
          },
        },
      },
      {
        id: "tpl8-weighted",
        type: "custom_formula",
        position: { x: 520, y: 320 },
        data: {
          label: "Weighted Control",
          customInputs: ["sum_temp", "deviation"],
          customOutputs: ["weighted_flow"],
          customFormulas: {
            weighted_flow: "sum_temp * 0.4 + deviation * 2",
          },
        },
      },
      {
        id: "tpl8-pressure",
        type: "pressure_sensor",
        position: { x: 760, y: 220 },
        data: { label: "Fusion Pressure" },
      },
    ],
    edges: [
      {
        id: "tpl8-edge-1",
        source: "tpl8-temp-1",
        sourceHandle: "measured_temp",
        target: "tpl8-aggregator",
        targetHandle: "t1",
      },
      {
        id: "tpl8-edge-2",
        source: "tpl8-temp-2",
        sourceHandle: "measured_temp",
        target: "tpl8-aggregator",
        targetHandle: "t2",
      },
      {
        id: "tpl8-edge-3",
        source: "tpl8-temp-3",
        sourceHandle: "measured_temp",
        target: "tpl8-aggregator",
        targetHandle: "t3",
      },
      {
        id: "tpl8-edge-4",
        source: "tpl8-aggregator",
        sourceHandle: "sum_temp",
        target: "tpl8-differencer",
        targetHandle: "sum_temp",
      },
      {
        id: "tpl8-edge-5",
        source: "tpl8-aggregator",
        sourceHandle: "sum_temp",
        target: "tpl8-weighted",
        targetHandle: "sum_temp",
      },
      {
        id: "tpl8-edge-6",
        source: "tpl8-differencer",
        sourceHandle: "deviation",
        target: "tpl8-weighted",
        targetHandle: "deviation",
      },
      {
        id: "tpl8-edge-7",
        source: "tpl8-weighted",
        sourceHandle: "weighted_flow",
        target: "tpl8-pressure",
        targetHandle: "flow_rate",
      },
    ],
  },
  {
    id: "adaptive-heat-loop",
    name: "Adaptive Heat Loop",
    desc: "Predictive gain and variance feed adaptive control before a secondary pressure hop.",
    icon: "🔁",
    complexity: 9,
    nodes: [
      {
        id: "tpl9-temp",
        type: "temperature_sensor",
        position: { x: 40, y: 220 },
        data: { label: "Surface Temp" },
      },
      {
        id: "tpl9-pressure",
        type: "pressure_sensor",
        position: { x: 260, y: 220 },
        data: { label: "Observed Pressure" },
      },
      {
        id: "tpl9-predictor",
        type: "custom_formula",
        position: { x: 460, y: 120 },
        data: {
          label: "Predictor",
          customInputs: ["measured_temp"],
          customOutputs: ["predicted_gain"],
          customFormulas: {
            predicted_gain: "measured_temp * 0.3 + 2",
          },
        },
      },
      {
        id: "tpl9-variance",
        type: "custom_formula",
        position: { x: 460, y: 320 },
        data: {
          label: "Variance",
          customInputs: ["measured_pressure"],
          customOutputs: ["variance_bias"],
          customFormulas: {
            variance_bias: "Math.max(0, measured_pressure - 5)",
          },
        },
      },
      {
        id: "tpl9-controller",
        type: "custom_formula",
        position: { x: 660, y: 200 },
        data: {
          label: "Adaptive Control",
          customInputs: ["predicted_gain", "variance_bias"],
          customOutputs: ["adaptive_flow"],
          customFormulas: {
            adaptive_flow: "predicted_gain - variance_bias * 0.05 + 2",
          },
        },
      },
      {
        id: "tpl9-pressure-final",
        type: "pressure_sensor",
        position: { x: 880, y: 200 },
        data: { label: "Adaptive Pressure" },
      },
    ],
    edges: [
      {
        id: "tpl9-edge-1",
        source: "tpl9-temp",
        sourceHandle: "measured_temp",
        target: "tpl9-pressure",
        targetHandle: "flow_rate",
      },
      {
        id: "tpl9-edge-2",
        source: "tpl9-temp",
        sourceHandle: "measured_temp",
        target: "tpl9-predictor",
        targetHandle: "measured_temp",
      },
      {
        id: "tpl9-edge-3",
        source: "tpl9-pressure",
        sourceHandle: "measured_pressure",
        target: "tpl9-variance",
        targetHandle: "measured_pressure",
      },
      {
        id: "tpl9-edge-4",
        source: "tpl9-predictor",
        sourceHandle: "predicted_gain",
        target: "tpl9-controller",
        targetHandle: "predicted_gain",
      },
      {
        id: "tpl9-edge-5",
        source: "tpl9-variance",
        sourceHandle: "variance_bias",
        target: "tpl9-controller",
        targetHandle: "variance_bias",
      },
      {
        id: "tpl9-edge-6",
        source: "tpl9-controller",
        sourceHandle: "adaptive_flow",
        target: "tpl9-pressure-final",
        targetHandle: "flow_rate",
      },
      {
        id: "tpl9-edge-7",
        source: "tpl9-controller",
        sourceHandle: "adaptive_flow",
        target: "tpl9-pressure-final",
        targetHandle: "valve_restriction",
      },
    ],
  },
  {
    id: "predictive-orchestrator",
    name: "Predictive Orchestrator",
    desc: "Trend, variance, and control math chain together before a high-fidelity pressure output.",
    icon: "🧩",
    complexity: 10,
    nodes: [
      {
        id: "tpl10-temp",
        type: "temperature_sensor",
        position: { x: 40, y: 160 },
        data: { label: "Trend Sensor" },
      },
      {
        id: "tpl10-pressure",
        type: "pressure_sensor",
        position: { x: 40, y: 320 },
        data: { label: "Process Pressure" },
      },
      {
        id: "tpl10-trend",
        type: "custom_formula",
        position: { x: 320, y: 120 },
        data: {
          label: "Trend",
          customInputs: ["measured_temp"],
          customOutputs: ["trend_signal"],
          customFormulas: {
            trend_signal: "measured_temp * 0.15 + 1",
          },
        },
      },
      {
        id: "tpl10-variance",
        type: "custom_formula",
        position: { x: 320, y: 320 },
        data: {
          label: "Variance",
          customInputs: ["measured_temp", "measured_pressure"],
          customOutputs: ["variance_signal"],
          customFormulas: {
            variance_signal: "Math.abs(measured_temp - measured_pressure * 0.1)",
          },
        },
      },
      {
        id: "tpl10-control",
        type: "custom_formula",
        position: { x: 560, y: 220 },
        data: {
          label: "Control Mix",
          customInputs: ["trend_signal", "variance_signal"],
          customOutputs: ["control_flow", "control_bias"],
          customFormulas: {
            control_flow: "trend_signal * 0.8 + variance_signal * 0.05",
            control_bias: "variance_signal * 0.02",
          },
        },
      },
      {
        id: "tpl10-adjust",
        type: "custom_formula",
        position: { x: 760, y: 220 },
        data: {
          label: "Flow Adjuster",
          customInputs: ["control_flow", "control_bias"],
          customOutputs: ["adjusted_flow"],
          customFormulas: {
            adjusted_flow: "control_flow + control_bias",
          },
        },
      },
      {
        id: "tpl10-pressure-final",
        type: "pressure_sensor",
        position: { x: 960, y: 220 },
        data: { label: "Predictive Output" },
      },
    ],
    edges: [
      {
        id: "tpl10-edge-1",
        source: "tpl10-temp",
        sourceHandle: "measured_temp",
        target: "tpl10-trend",
        targetHandle: "measured_temp",
      },
      {
        id: "tpl10-edge-2",
        source: "tpl10-temp",
        sourceHandle: "measured_temp",
        target: "tpl10-variance",
        targetHandle: "measured_temp",
      },
      {
        id: "tpl10-edge-3",
        source: "tpl10-pressure",
        sourceHandle: "measured_pressure",
        target: "tpl10-variance",
        targetHandle: "measured_pressure",
      },
      {
        id: "tpl10-edge-4",
        source: "tpl10-trend",
        sourceHandle: "trend_signal",
        target: "tpl10-control",
        targetHandle: "trend_signal",
      },
      {
        id: "tpl10-edge-5",
        source: "tpl10-variance",
        sourceHandle: "variance_signal",
        target: "tpl10-control",
        targetHandle: "variance_signal",
      },
      {
        id: "tpl10-edge-6",
        source: "tpl10-control",
        sourceHandle: "control_flow",
        target: "tpl10-adjust",
        targetHandle: "control_flow",
      },
      {
        id: "tpl10-edge-7",
        source: "tpl10-control",
        sourceHandle: "control_bias",
        target: "tpl10-adjust",
        targetHandle: "control_bias",
      },
      {
        id: "tpl10-edge-8",
        source: "tpl10-adjust",
        sourceHandle: "adjusted_flow",
        target: "tpl10-pressure-final",
        targetHandle: "flow_rate",
      },
      {
        id: "tpl10-edge-9",
        source: "tpl10-adjust",
        sourceHandle: "adjusted_flow",
        target: "tpl10-pressure-final",
        targetHandle: "valve_restriction",
      },
    ],
  },
];

export default TemplateRegistry;
